# Generated by Django 5.1.6 on 2025-02-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_profile_marks_profile_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='sam@gmail.com', max_length=45),
            preserve_default=False,
        ),
    ]
