# Generated by Django 5.1.6 on 2025-02-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_profile__date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='_date',
            new_name='admit_date',
        ),
    ]
